import { CommodityItem } from '../src/types.js';

export const CONO_SUR_COMMODITIES: CommodityItem[] = [
  {
    id: 'commodity-soja',
    symbol: 'SOYB / ZS',
    name: 'Soja Grano (FOB Rosario / CBOT)',
    category: 'AGRO_GRAINS',
    price: 482.00,
    unit: 'USD / Tonelada',
    change24h: -0.65,
    changeWeek: 1.40,
    high52w: 515.00,
    low52w: 435.00,
    lastUpdated: new Date().toISOString(),
    benchmark: 'CBOT / FOB Up-River Paraná & Paranaguá',
    keyCountries: ['AR', 'BR', 'PY', 'UY', 'BO'],
    strategicRelevance: 'Brasil y Argentina concentran >50% de la oferta exportable global de soja. Motor principal de ingreso de divisas y recaudación fiscal en el Cono Sur.',
    geopoliticalDrivers: [
      'Calado y tarifas de dragado en la Hidrovía Paraná-Paraguay',
      'Esquema de retenciones y liquidación de divisas en Argentina',
      'Ritmo de compras de la molienda estatal y privada en China',
      'Riesgos climáticos (La Niña) en la cuenca del Río de la Plata'
    ],
    logisticsAxis: 'Ruta Fluvial Hidrovía Paraná-Paraguay (Puertos de Rosario, San Lorenzo, Paranaguá y Nueva Palmira)',
    sparkline: [485.2, 484.9, 478.9, 482.0]
  },
  {
    id: 'commodity-harina-soja',
    symbol: 'ZM / SOYMEAL',
    name: 'Harina de Soja (FOB Gran Rosario)',
    category: 'AGRO_GRAINS',
    price: 397.90,
    unit: 'USD / Tonelada',
    change24h: 0.05,
    changeWeek: 1.85,
    high52w: 440.00,
    low52w: 345.00,
    lastUpdated: new Date().toISOString(),
    benchmark: 'FOB Gran Rosario / Up-River',
    keyCountries: ['AR', 'BR', 'PY'],
    strategicRelevance: 'Argentina es el exportador #1 mundial indiscutido de harina de soja (clave para la alimentación pecuaria en Europa y Sudeste Asiático).',
    geopoliticalDrivers: [
      'Regulación ambiental europea contra la deforestación (EUDR)',
      'Capacidad ociosa del polo de crushing en el Gran Rosario',
      'Diferenciales arancelarios entre grano sin procesar y subproductos'
    ],
    logisticsAxis: 'Terminales Portuarias de San Lorenzo, Puerto San Martín y Timbúes (Río Paraná)',
    sparkline: [397.8, 406.4, 390.9, 397.9]
  },
  {
    id: 'commodity-cobre',
    symbol: 'HG / CU-COMEX',
    name: 'Cobre Refinado Grado A (COMEX / LME)',
    category: 'METALS_MINING',
    price: 6.79,
    unit: 'USD / Libra (lb)',
    change24h: 5.60,
    changeWeek: 7.80,
    high52w: 6.95,
    low52w: 4.10,
    lastUpdated: new Date().toISOString(),
    benchmark: 'COMEX / London Metal Exchange (LME)',
    keyCountries: ['CL', 'AR'],
    strategicRelevance: 'Chile aporta el 24% de la producción mundial de cobre (Codelco / Escondida). Argentina reactiva megaproyectos en la cordillera (Josemaría, Taca Taca, Los Azules).',
    geopoliticalDrivers: [
      'Aceleración de la transición energética y redes de electromovilidad global',
      'Leyes de mineral decrecientes y disponibilidad hídrica en el Desierto de Atacama',
      'Sanciones y aranceles comerciales entre Estados Unidos y China',
      'Negociaciones laborales y convenios colectivos en minas chilenas'
    ],
    logisticsAxis: 'Puertos del Pacífico Norte de Chile (Antofagasta, Mejillones, San Antonio) y pasos cordilleranos',
    sparkline: [6.43, 6.59, 6.61, 6.79]
  },
  {
    id: 'commodity-litio',
    symbol: 'Li2CO3 / LITH',
    name: 'Carbonato de Litio 99.5% Grado Batería',
    category: 'METALS_MINING',
    price: 11950.00,
    unit: 'USD / Tonelada',
    change24h: 1.80,
    changeWeek: 3.20,
    high52w: 16500.00,
    low52w: 9200.00,
    lastUpdated: new Date().toISOString(),
    benchmark: 'S&P Global Platts / Fastmarkets Battery Grade CIF Asia',
    keyCountries: ['CL', 'AR', 'BO'],
    strategicRelevance: 'El Triángulo del Litio (Salar de Atacama, Hombre Muerto, Olaroz, Uyuni) alberga más del 55% de las reservas mundiales del metal crítico para baterías EV.',
    geopoliticalDrivers: [
      'Alianzas estratégicas Estado-Privados (Codelco-SQM en Chile, YLB en Bolivia)',
      'Tecnologías de Extracción Directa de Litio (EDL) frente a piscinas de evaporación',
      'Geopolítica de cadenas de valor entre fabricantes de baterías asiáticos, EE.UU. y Europa',
      'Régimen de regalías mineras provinciales en el Noroeste Argentino (NOA)'
    ],
    logisticsAxis: 'Paso de Jama / Paso de Sico hacia puertos de Antofagasta/Mejillones y Corredor Bioceánico',
    sparkline: [11600, 11750, 11800, 11950]
  },
  {
    id: 'commodity-trigo',
    symbol: 'WHEAT / ZW',
    name: 'Trigo Pan (FOB Cono Sur / CBOT)',
    category: 'AGRO_GRAINS',
    price: 265.20,
    unit: 'USD / Tonelada',
    change24h: -1.20,
    changeWeek: 0.85,
    high52w: 285.00,
    low52w: 215.00,
    lastUpdated: new Date().toISOString(),
    benchmark: 'FOB Puertos Argentinos & CBOT',
    keyCountries: ['AR', 'BR', 'UY'],
    strategicRelevance: 'Garante de la seguridad alimentaria regional. Argentina abastece más del 80% de la importación triguera de los molinos de Brasil.',
    geopoliticalDrivers: [
      'Disrupciones navales en el Mar Negro y corredores de granos de Europa del Este',
      'Rendimientos de la cosecha de invierno en la Pampa Húmeda y Río Grande do Sul',
      'Acuerdos de cupos y compensaciones arancelarias intra-Mercosur'
    ],
    logisticsAxis: 'Puertos de aguas profundas de Bahía Blanca, Quequén y Terminales del Río de la Plata',
    sparkline: [268.5, 267.1, 262.4, 265.2]
  },
  {
    id: 'commodity-maiz',
    symbol: 'CORN / ZC',
    name: 'Maíz Amarillo (FOB Santos-Rosario)',
    category: 'AGRO_GRAINS',
    price: 209.90,
    unit: 'USD / Tonelada',
    change24h: -0.20,
    changeWeek: 1.15,
    high52w: 235.00,
    low52w: 175.00,
    lastUpdated: new Date().toISOString(),
    benchmark: 'CBOT / FOB Santos & Rosario',
    keyCountries: ['BR', 'AR', 'PY'],
    strategicRelevance: 'Brasil (segunda zafra / safrinha) y Argentina son los mayores competidores de exportación de maíz frente a EE.UU., alimentando a Medio Oriente y Asia.',
    geopoliticalDrivers: [
      'Demanda récord de maíz para producción de etanol en el Centro-Oeste brasileño',
      'Monitoreo biológico contra plagas (chicharrita del maíz / Spiroplasma)',
      'Costos de flete en trenes de Rumo hacia Santos e Hidrovía Paraná'
    ],
    logisticsAxis: 'Puertos de Santos, Paranaguá, Rosario y Barcazas desde Alto Paraná',
    sparkline: [210.3, 208.8, 207.7, 209.9]
  },
  {
    id: 'commodity-petroleo-wti',
    symbol: 'CL / WTI',
    name: 'Petróleo Crudo WTI / Medanito',
    category: 'ENERGY_HYDROCARBONS',
    price: 93.44,
    unit: 'USD / Barril (bbl)',
    change24h: -1.80,
    changeWeek: -3.50,
    high52w: 102.50,
    low52w: 72.00,
    lastUpdated: new Date().toISOString(),
    benchmark: 'NYMEX WTI / FOB Puerto Rosales (Medanito Shale)',
    keyCountries: ['AR', 'BR'],
    strategicRelevance: 'Vaca Muerta (Argentina) incrementa su saldo exportable de crudo liviano Medanito, mientras Brasil expande su extracción récord en el Pre-Sal oceánico.',
    geopoliticalDrivers: [
      'Capacidad de evacuación de oleoductos (Duplicar de Oldelval y Oleoducto Trasandino Otasa a Chile)',
      'Decisiones de cuotas de producción de la OPEP+ y tensión en el Estrecho de Ormuz',
      'Desarrollo de terminales offshore en el litoral bonaerense y Bahía Blanca'
    ],
    logisticsAxis: 'Oleoducto Otasa (Concepción, Chile), Terminal Puerto Rosales (Bahía Blanca) y São Sebastião',
    sparkline: [102.4, 101.9, 100.3, 93.4]
  },
  {
    id: 'commodity-gas-natural',
    symbol: 'NG / GAS',
    name: 'Gas Natural (Henry Hub / Cono Sur Spot)',
    category: 'ENERGY_HYDROCARBONS',
    price: 2.86,
    unit: 'USD / MMBtu',
    change24h: -1.10,
    changeWeek: 3.40,
    high52w: 3.45,
    low52w: 1.85,
    lastUpdated: new Date().toISOString(),
    benchmark: 'Henry Hub NYMEX / Gasoductos Cono Sur',
    keyCountries: ['AR', 'BO', 'BR', 'CL'],
    strategicRelevance: 'Eje de la integración energética regional: Reversión del Gasoducto Norte para llevar gas de Vaca Muerta a Brasil a través de la infraestructura de Bolivia.',
    geopoliticalDrivers: [
      'Declinación de la producción en megacampos gasíferos bolivianos (San Alberto / Margarita)',
      'Tarifas de peaje y habilitación técnica del sistema Gasbol para exportación tripartita',
      'Demanda del parque industrial pesada de São Paulo y plantas térmicas del Cono Sur',
      'Proyectos de plantas flotantes de GNL (FLNG) para exportación a ultramar'
    ],
    logisticsAxis: 'Gasoducto Néstor Kirchner, Gasoducto Norte / Yacuiba, Red Gasbol Bolivia-Brasil',
    sparkline: [2.68, 2.72, 2.75, 2.79, 2.81, 2.84, 2.88]
  },
  {
    id: 'commodity-mineral-hierro',
    symbol: 'FE62 / IODEX',
    name: 'Mineral de Hierro 62% Fe (CFR China)',
    category: 'METALS_MINING',
    price: 105.80,
    unit: 'USD / Tonelada',
    change24h: 0.65,
    changeWeek: -1.20,
    high52w: 142.00,
    low52w: 91.00,
    lastUpdated: new Date().toISOString(),
    benchmark: 'S&P Global Platts IODEX 62% Fe CFR Qingdao',
    keyCountries: ['BR', 'BO'],
    strategicRelevance: 'Brasil es el #2 productor mundial de mineral de hierro (Vale). Bolivia desarrolla el megayacimiento del Mutún en la frontera con el Río Paraguay.',
    geopoliticalDrivers: [
      'Estímulos a la construcción e industria siderúrgica pesada en China',
      'Logística fluvial de barcazas de mineral desde Corumbá por el Río Paraguay hacia el Atlántico',
      'Descarbonización de la siderurgia global mediante pellets de hierro de alta pureza'
    ],
    logisticsAxis: 'Terminal Marítima de Ponta da Madeira, Puerto de Tubarão y Barcazas desde Corumbá / Mutún',
    sparkline: [106.5, 107.0, 105.0, 104.2, 105.1, 105.2, 105.8]
  },
  {
    id: 'commodity-carne-vacuna',
    symbol: 'BEEF / NOV',
    name: 'Novillo Mercosur (Exportación)',
    category: 'AGRO_GRAINS',
    price: 3.82,
    unit: 'USD / Kg Carcasa (Gancho)',
    change24h: 0.50,
    changeWeek: 1.85,
    high52w: 4.15,
    low52w: 3.30,
    lastUpdated: new Date().toISOString(),
    benchmark: 'Índice Novillo Mercosur (Promedio Ponderado AR-BR-UY-PY)',
    keyCountries: ['BR', 'AR', 'UY', 'PY'],
    strategicRelevance: 'El bloque Mercosur es el principal polo exportador de proteína bovina del mundo, abasteciendo a China, EE.UU., Israel y la Unión Europea.',
    geopoliticalDrivers: [
      'Apertura de nuevos mercados sanitarios libres de aftosa sin vacunación',
      'Cumplimiento de trazabilidad satelital individual y certificaciones de huella de carbono',
      'Diferenciales de costos de faena e impuestos entre Argentina, Brasil y Uruguay'
    ],
    logisticsAxis: 'Frigoríficos de exportación con salida por puertos de Santos, Buenos Aires, Montevideo y Asunción',
    sparkline: [3.72, 3.75, 3.78, 3.76, 3.80, 3.81, 3.82]
  },
  {
    id: 'commodity-celulosa',
    symbol: 'PULP / BHKP',
    name: 'Celulosa Kraft BHKP (Eucalipto CIF Asia)',
    category: 'FORESTRY_PULP',
    price: 685.00,
    unit: 'USD / Tonelada',
    change24h: 0.40,
    changeWeek: 0.90,
    high52w: 780.00,
    low52w: 590.00,
    lastUpdated: new Date().toISOString(),
    benchmark: 'Bleached Hardwood Kraft Pulp CIF China / Europa',
    keyCountries: ['UY', 'BR', 'CL'],
    strategicRelevance: 'La celulosa es el primer producto de exportación de Uruguay (UPM y Montes del Plata) y un rubro estratégico en Brasil (Suzano) y Chile (Arauco, CMPC).',
    geopoliticalDrivers: [
      'Demanda global de embalajes sostenibles para sustitución de plásticos de un solo uso',
      'Operatividad y capacidad del Ferrocarril Central y dragado en el Puerto de Montevideo',
      'Desarrollo de nuevas cuencas forestales y proyectos de biorrefinerías en el Cono Sur'
    ],
    logisticsAxis: 'Terminal especializada UPM en el Puerto de Montevideo, Terminales Portuarias de Santos y Coronel',
    sparkline: [678.0, 679.5, 681.0, 680.0, 682.5, 684.0, 685.0]
  }
];
